---
title: "Gov 50 Final Project"
author: "Shania Hurtado"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Part 1: Project thoughts

I am interested in exploring data related to the relationship between the US exports of crude oil to China and China's military spending from 2000-2010. 

## Part 2: Proposal for Project

My research question is: To what extent are China's foreign oil trade policies motivated by increasing military capabilities?

I hypothesize that China's foreign oil trade policy, particularly ith the United States both drives and is driven by strengthening military capabilities. I hypothesize that this could be explained by historical memory and China's past with the century of humiliation. I will use data from the U.S. Energy Information Administration from 2000-2010 and from the World Bank. The explanatory variable of interest is the U.S. exports of crude oil to China in thousands of barrels, and the outcome variable of interest is military expenditures (% GDP) in China. 

The observed pattern would provide support for my hypothesis in observing a correlation between a greater dependency on US oil exports and an increase in military expenditures. An increasing pattern would suggest that as China's reliance on US crude oil increases, military spending in China also increases. This result would accept my hypothesis. The observed pattern that would disprove my hypothesis is that a decreasing pattern would suggest a negative relationship such that as dependence on US oil increase, military spending decreases. 


```{r}
library(tidyverse)
library(readxl)
library(dplyr)
 
# Data from  U.S. Energy Information Administration: https://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=PET&s=MTTEXCH1&f=M
data_oil <- data.frame(Year = c(2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010),
                   oil_import = c(1105, 2044, 5280, 8915, 4917, 4407 , 3986 , 4970 , 4875, 15954, 18894))
plot <- 
  ggplot(data = data_oil,
                    mapping = aes(x = Year,
                                  y = oil_import)) +
  geom_point() + labs(x = "Year",
                        y = "Oil Imports from United States (in thousand barrels)",
                      title = "Oil Imports in China from United States (in thousand barrels), 2000-2010", caption = "Source: U.S. Energy Information Administration") +
  scale_x_continuous(breaks = c(2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010))
plot

data_military <- read_excel("militarydata.xls", sheet = "Data")
data_military <- data_military |>
  filter(`Country Name` == "China") |>
  subset(select = -c(`Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`))

data_military <- data_military |>
  pivot_longer(cols= everything()) 
  
data_military <- data_military |>
  filter(name >= 2000 & name <= 2010) |>
  mutate(new_value = value / 1000000000)

data_military <- data_military |>
  rename("Year" = "name")
             
data_military <- transform(data_military, Year = as.numeric(Year))

data_military <- data_military |>
  left_join(data_oil, by = "Year") |>
    subset(select = -c(`value`))

plot_2 <- 
  ggplot(data = data_military,
                    mapping = aes(x = Year,
                                  y = new_value)) +
  geom_point() + labs(x = "Year",
                        y = "China Military Expenditures (USD billions)",
                      title = "China Military Expenditures (USD billions), 2000-2010",
                      caption = "Source: The World Bank") +
    scale_x_continuous(breaks = c(2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010))
plot_2

library(broom)
fit_1 <- lm(new_value ~ oil_import, data = data_military)
fit_1 |>
  broom::tidy() |>
  select(term, estimate) |>  
  knitr::kable()

```
The coefficient of 0.0041704 for the explanatory variable, oil imports from the United States into China, is extremely small, signifying that there is an insignificant correlation between US imports of oil into China and military expenditures. This does not support my hypothesis and shows that oil imports from the United States do not have a significant relationship with military expenditures. 